Repository devnogi/devnogi-community-server, pull requests merged in 2025-07, with the labels that each got.

#24 feat: comment 리팩토링
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentConverter.java
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentService.java
  src/main/java/until/the/eternity/dcs/domain/comment/dto/response/CommentPageResponseItem.java
  src/main/java/until/the/eternity/dcs/domain/post/exception/CommentExceptionCode.java
  src/main/java/until/the/eternity/dcs/domain/post/exception/CommentModifyForbiddenException.java
  src/main/java/until/the/eternity/dcs/domain/post/exception/CommentNotFoundException.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentServiceTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/entity/CommentTest.java
  src/test/java/until/the/eternity/dcs/infrastructure/FakeCommentRepository.java
Labels: 🛠️refactor

#29 feat: 댓글 좋아요 엔티티 및 DTO 구현
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentLikeConverter.java
  src/main/java/until/the/eternity/dcs/domain/comment/dto/request/CommentLikeToggleRequest.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/CommentLike.java
  src/main/resources/db/migration/V20250707002007__create_comment_like.sql
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentLikeConverterTest.java
Labels: ✨feature

#33 feat: post like dto 구현
  src/main/java/until/the/eternity/dcs/domain/post/application/PostLikeConverter.java
  src/main/java/until/the/eternity/dcs/domain/post/application/PostService.java
  src/main/java/until/the/eternity/dcs/domain/post/dto/request/PostLikeCreateRequest.java
  src/main/java/until/the/eternity/dcs/domain/post/dto/response/PostDetailResponse.java
  src/test/java/until/the/eternity/dcs/domain/postLike/application/PostLikeConverterTest.java
Labels: ✨feature

#35 refactor: Repository 구조 단순화
  src/main/java/until/the/eternity/dcs/domain/board/entity/BoardRepository.java
  src/main/java/until/the/eternity/dcs/domain/board/infrastructure/BoardRepositoryImpl.java
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentService.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/CommentLikeRepository.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/CommentRepository.java
  src/main/java/until/the/eternity/dcs/domain/comment/infrastructure/CommentLikeRepositoryImpl.java
  src/main/java/until/the/eternity/dcs/domain/comment/infrastructure/CommentRepositoryImpl.java
  src/test/java/until/the/eternity/dcs/domain/board/application/BoardConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/board/application/BoardServiceTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentLikeConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentServiceTest.java
  src/test/java/until/the/eternity/dcs/infrastructure/FakeBoardRepository.java
  src/test/java/until/the/eternity/dcs/infrastructure/FakeCommentLikeRepository.java
  src/test/java/until/the/eternity/dcs/infrastructure/FakeCommentRepository.java
Labels: 🛠️refactor

#39 feat: postLike crud 구현
  src/main/java/until/the/eternity/dcs/domain/post/application/PostLikeConverter.java
  src/main/java/until/the/eternity/dcs/domain/post/application/PostService.java
  src/main/java/until/the/eternity/dcs/domain/post/entity/Post.java
  src/main/java/until/the/eternity/dcs/domain/post/entity/PostLike.java
  src/main/java/until/the/eternity/dcs/domain/post/infrastructure/PostLikeRepository.java
  src/main/java/until/the/eternity/dcs/domain/post/presentation/PostController.java
  src/test/java/until/the/eternity/dcs/domain/post/application/PostServiceTest.java
  src/test/java/until/the/eternity/dcs/domain/postLike/application/PostLikeConverterTest.java
Labels: ✨feature

#41 infra: 테스트 커버리지 측정
  .github/workflows/pull-request-test.yml
  build.gradle.kts
  codecov.yml
  gradle/jacoco.gradle.kts
Labels: 🗂️chore

#45 feat: report 관련 DTO, converter 구현
  .githooks/pre-commit
  src/main/java/until/the/eternity/dcs/domain/report/application/ReportConverter.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/request/ReportCreateRequest.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/request/ReportRepliedUpdateRequest.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/request/ReportRevivedUpdateRequest.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRepliedDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRepliedSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRevivedDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRevivedSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/entitiy/Report.java
  src/main/java/until/the/eternity/dcs/domain/report/enums/ReportStatus.java
Labels: ✨feature

#48 fix: CI가 멈추는 버그 해결을 위한 워크플로우 개선
  .github/workflows/pull-request-test.yml
Labels: 🔧fix

#50 feat: report test code 작성
  src/main/java/until/the/eternity/dcs/domain/report/application/ReportConverter.java
  src/main/java/until/the/eternity/dcs/domain/report/application/ReportService.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/request/ReportCreateRequest.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRepliedDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRepliedSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportReportedDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportReportedSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRevivedDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/dto/response/ReportRevivedSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/report/enums/ReportTargetType.java
  src/main/java/until/the/eternity/dcs/domain/report/exception/CategoryNotFoundException.java
  src/main/java/until/the/eternity/dcs/domain/report/exception/ReportExceptionCode.java
  src/main/java/until/the/eternity/dcs/domain/report/exception/TargetNotFoundException.java
  src/main/java/until/the/eternity/dcs/domain/report/infrastructure/ReportRepository.java
  src/test/java/until/the/eternity/dcs/domain/post/application/PostLikeConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/report/application/ReportConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/report/application/ReportServiceTest.java
  src/test/java/until/the/eternity/dcs/domain/report/entity/ReportTest.java
Labels: ✨feature

#52 refactor: comment meta 생성
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentConverter.java
  src/main/java/until/the/eternity/dcs/domain/comment/application/CommentService.java
  src/main/java/until/the/eternity/dcs/domain/comment/dto/response/CommentPageResponseItem.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/Comment.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/CommentMeta.java
  src/main/java/until/the/eternity/dcs/domain/comment/entity/CommentMetaRepository.java
  src/main/java/until/the/eternity/dcs/domain/comment/exception/CommentExceptionCode.java
  src/main/java/until/the/eternity/dcs/domain/comment/exception/CommentNotLikedYetException.java
  src/main/java/until/the/eternity/dcs/domain/comment/infrastructure/JpaCommentMetaRepository.java
  src/main/resources/db/migration/R__add_dummy_data.sql
  src/main/resources/db/migration/V20250723002007__create_comment_meta.sql
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/comment/application/CommentServiceTest.java
Labels: 🛠️refactor

#55 feat: post meta 테이블 생성, post meta 기존 로직 테스트코드에 반영
  src/main/java/until/the/eternity/dcs/domain/post/application/PostConverter.java
  src/main/java/until/the/eternity/dcs/domain/post/application/PostService.java
  src/main/java/until/the/eternity/dcs/domain/post/dto/response/PostDetailResponse.java
  src/main/java/until/the/eternity/dcs/domain/post/dto/response/PostPersistResponse.java
  src/main/java/until/the/eternity/dcs/domain/post/dto/response/PostSummaryResponse.java
  src/main/java/until/the/eternity/dcs/domain/post/entity/Post.java
  src/main/java/until/the/eternity/dcs/domain/post/entity/PostMeta.java
  src/main/java/until/the/eternity/dcs/domain/post/infrastructure/PostMetaRepository.java
  src/main/java/until/the/eternity/dcs/domain/post/presentation/PostController.java
  src/main/resources/db/migration/R__add_dummy_data.sql
  src/main/resources/db/migration/V20250724212200__create_post_meat.sql
  src/test/java/until/the/eternity/dcs/domain/post/application/PostConverterTest.java
  src/test/java/until/the/eternity/dcs/domain/post/application/PostServiceTest.java
Labels: ✨feature

#60 Chore: add redis
  build.gradle.kts
  docker-compose.yaml
  src/main/java/until/the/eternity/dcs/DcsApplication.java
  src/main/java/until/the/eternity/dcs/common/config/RedisConfig.java
  src/main/resources/application.yml
  src/main/resources/db/migration/R__add_dummy_data.sql
Labels: 🗂️chore

#62 chore: 배포 서버에 Redis 추가
  Dockerfile
  src/main/resources/application.yml
Labels: 🗂️chore
